import {
  Analytics01Icon,
  ChartLineData01Icon,
  CubeIcon,
  FolderLibraryIcon,
  ChampionIcon,
  Coins01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  FlashIcon,
  BoltIcon,
  DollarCircleIcon,
  Database01Icon,
  EnergyIcon,
  Calendar03Icon,
  Layers01Icon,
  MinusSignIcon,
  SquareIcon,
  Copy01Icon,
  ServerStack01Icon,
  Cancel01Icon,
  Refresh01Icon,
  Moon02Icon,
  Sun03Icon,
  Settings01Icon,
  Clock01Icon,
  Time04Icon,
  StarAward01Icon,
  Rocket01Icon,
  Award01Icon,
  GemIcon,
  Diamond01Icon,
  Crown02Icon,
  Infinity02Icon,
  Leaf01Icon,
  Wallet01Icon,
  Compass01Icon,
  Fire02Icon,
  SunriseIcon,
  Target01Icon,
  SparklesIcon,
  PieChart01Icon,
  Medal01Icon
} from "@hugeicons/core-free-icons";

export const ICON = {
  overview: Analytics01Icon,
  activity: ChartLineData01Icon,
  models: CubeIcon,
  projects: FolderLibraryIcon,
  providers: ServerStack01Icon,
  badges: ChampionIcon,

  tokens: Coins01Icon,
  input: ArrowDown01Icon,
  output: ArrowUp01Icon,
  requests: FlashIcon,
  cost: DollarCircleIcon,
  cache: Database01Icon,
  avg: EnergyIcon,
  calendar: Calendar03Icon,
  sessions: Layers01Icon,
  composition: PieChart01Icon,

  minimize: MinusSignIcon,
  maximize: SquareIcon,
  restore: Copy01Icon,
  close: Cancel01Icon,
  refresh: Refresh01Icon,
  moon: Moon02Icon,
  sun: Sun03Icon,
  settings: Settings01Icon,
  clock: Clock01Icon,
  time: Time04Icon,
  source: Database01Icon,

  b_first: StarAward01Icon,
  b_century: BoltIcon,
  b_power: Rocket01Icon,
  b_marathon: Award01Icon,
  b_millionaire: GemIcon,
  b_tenmillion: Diamond01Icon,
  b_hundredm: Layers01Icon,
  b_billion: Crown02Icon,
  b_infinite: Infinity02Icon,
  b_cache: Leaf01Icon,
  b_spender: Wallet01Icon,
  b_polyglot: CubeIcon,
  b_explorer: Compass01Icon,
  b_consistent: Calendar03Icon,
  b_streak: Fire02Icon,
  b_nightowl: Moon02Icon,
  b_earlybird: SunriseIcon,
  b_target: Target01Icon,
  b_spark: SparklesIcon,
  b_medal: Medal01Icon
} as const;

export type IconKey = keyof typeof ICON;
